# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true # const 선언 가능한 경우 const
    avoid_print: true # 디버깅은 logger 사용
    unnecessary_this: true # this 키워드가 없어도 되는 경우 사용하지 않도록
    always_declare_return_types: true # 함수의 반환타입 명시
    avoid_unnecessary_containers: true # 불필요한 Container 위젯 사용 피하기
    prefer_final_locals: true # 변경이 없는 지역변수를 final로 선언하라고 권장
